flags:
    Snowdrift:
        dev: true
packages:
- '.'
extra-deps:
    # Absent from LTS
    - dns-2.0.0
    - mime-0.4.0.2
    - github-0.13.2
    - libravatar-0.1.0.1
    - titlecase-0.1.0.1
    - yesod-markdown-0.9.4
    # Transitive dep of github
    - failure-0.2.0.3
    # bugfix updates newer than LTS (not actual dependencies, but dev tools)
    - yesod-bin-1.4.14
    - fast-tags-1.1.1
    - ghc-mod-5.4.0.0
    # Transitive deps of ghc-mod
    - cabal-helper-0.6.0.0
    - extra-1.4.2
    # fsnotify on OS X
    - hfsevents-0.1.5
resolver: lts-2.22
