flags:
    Snowdrift:
        dev: true
packages:
- '.'
extra-deps:
    # Absent from LTS
    - github-0.13.2
    - libravatar-0.1.0.1
    - mime-0.4.0.2
    - titlecase-0.1.0.1
    - yesod-markdown-0.10.0
    # Transitive dep of github
    - failure-0.2.0.3
    # bugfix updates newer than LTS (not actual dependencies, but dev tools)
    - fast-tags-1.1.1
resolver: lts-3.5
