flags:
    Snowdrift:
        dev: true
packages:
- '.'
extra-deps:
# Absent from LTS
- dns-2.0.0
- mime-0.4.0.2
- github-0.13.2
- libravatar-0.1.0.1
- titlecase-0.1.0.1
- yesod-markdown-0.9.4
# Transitive dep of github
- failure-0.2.0.3
# bugfix update newer than LTS
- yesod-bin-1.4.14
resolver: lts-2.21
