stanzas:
    - type: webapp
      exec: ../dist/build/Snowdrift/Snowdrift
      args:
          - production
      env:
          APPROOT: https://snowdrift.coop
          PGDATABASE: snowdrift_production
          PGUSER: snowdrift_production
      forward-env:
          - PGPASS
      hosts:
          - snowdrift.coop

    - type: background
      exec: ../dist/build/SnowdriftEmailDaemon/SnowdriftEmailDaemon
      env:
          PGDATABASE: snowdrift_production
          PGUSER: snowdrift_production
      forward-env:
          - PGPASS
      args:
          - '--db=production'
          - '--email=notifications@snowdrift.coop'

    - type: background
      exec: ../ops/manage-symlink

    # Redirect the https version of www. Since we're load-balanced, it
    # comes in on 80.
    - type: redirect
      hosts:
        - www.snowdrift.coop
      actions:
        - host: snowdrift.coop
          secure: true

extraFiles:
    - ../migrations
    # FIXME: This shouldn't be needed.
    - ../templates

# Assuming you have an awscli profile named 'snowdrift' that refers to the
# Snowdrift account, the server to copy to can be acquired with:
# $ aws --profile snowdrift ec2 describe-instances --instance-ids i-81a6df28 --query 'Reservations[].Instances[].PublicDnsName'
copy-to: ec2-54-152-177-195.compute-1.amazonaws.com:/opt/keter/incoming
