stanzas:
    - type: webapp
      exec: ../dist/build/Snowdrift/Snowdrift
      args:
          - production
      env:
          # FIXME: Remove dev after DNS switchover
          APPROOT: https://dev.snowdrift.coop
          PGDATABASE: snowdrift_production
          PGUSER: snowdrift_production
      forward-env:
          - PGPASS
      hosts:
          - snowdrift.coop
          # FIXME: Remove after dns switchover
          - dev.snowdrift.coop

    # - type: background
    #   exec: ../dist/build/SnowdriftEmailDaemon/SnowdriftEmailDaemon
    #   env:
    #       PGDATABASE: snowdrift_production
    #       PGUSER: snowdrift_production
    #   forward-env:
    #       - PGPASS
    #   args:
    #       - '--db=production'
    #       - '--email=notifications@snowdrift.coop'

    - type: background
      exec: manage-symlink

extraFiles:
    - ../migrations
    # FIXME: This shouldn't be needed.
    - ../templates

# FIXME: Remove dev after DNS switchover
copy-to: dev.snowdrift.coop:/opt/keter/incoming
