Default: &defaults
  host: "127.0.0.1"
  port: 3000
  approot: "http://localhost:3000"
  copyright: "2012-2015 snowdrift contributors"
  source: "https://github.com/snowdriftcoop/snowdrift"
  githubrepo: "snowdriftcoop/snowdrift"
  siteproject: "snowdrift"
  #analytics: UA-YOURCODE

Development:
  host: "*"
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://localhost:4003"
  port: 4003
  <<: *defaults
